{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/awsappflow\/appflowclienttypes\/privateconnectionprovisioningstate\/failuremessage"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AWSAppflow\/documentation\/AWSAppflow\/AppflowClientTypes\/PrivateConnectionProvisioningState\/failureMessage","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Specifies the private connection provisioning failure reason."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"failureMessage","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10AWSAppflow18AppflowClientTypesO34PrivateConnectionProvisioningStateV14failureMessageSSSgvp","modules":[{"name":"AWSAppflow"}]},"hierarchy":{"paths":[["doc:\/\/AWSAppflow\/documentation\/AWSAppflow","doc:\/\/AWSAppflow\/documentation\/AWSAppflow\/AppflowClientTypes","doc:\/\/AWSAppflow\/documentation\/AWSAppflow\/AppflowClientTypes\/PrivateConnectionProvisioningState"]]},"references":{"doc://AWSAppflow/documentation/AWSAppflow/AppflowClientTypes/PrivateConnectionProvisioningState/failureMessage":{"role":"symbol","title":"failureMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Specifies the private connection provisioning failure reason."}],"identifier":"doc:\/\/AWSAppflow\/documentation\/AWSAppflow\/AppflowClientTypes\/PrivateConnectionProvisioningState\/failureMessage","kind":"symbol","type":"topic","url":"\/documentation\/awsappflow\/appflowclienttypes\/privateconnectionprovisioningstate\/failuremessage"},"doc://AWSAppflow/documentation/AWSAppflow":{"role":"collection","title":"AWSAppflow","abstract":[],"identifier":"doc:\/\/AWSAppflow\/documentation\/AWSAppflow","kind":"symbol","type":"topic","url":"\/documentation\/awsappflow"},"doc://AWSAppflow/documentation/AWSAppflow/AppflowClientTypes":{"role":"symbol","title":"AppflowClientTypes","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppflowClientTypes"}],"abstract":[],"identifier":"doc:\/\/AWSAppflow\/documentation\/AWSAppflow\/AppflowClientTypes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppflowClientTypes"}],"url":"\/documentation\/awsappflow\/appflowclienttypes"},"doc://AWSAppflow/documentation/AWSAppflow/AppflowClientTypes/PrivateConnectionProvisioningState":{"role":"symbol","title":"AppflowClientTypes.PrivateConnectionProvisioningState","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrivateConnectionProvisioningState"}],"abstract":[{"type":"text","text":"Specifies the private connection provisioning state."}],"identifier":"doc:\/\/AWSAppflow\/documentation\/AWSAppflow\/AppflowClientTypes\/PrivateConnectionProvisioningState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PrivateConnectionProvisioningState"}],"url":"\/documentation\/awsappflow\/appflowclienttypes\/privateconnectionprovisioningstate"}}}