{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalServerException"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AWSAppflow\/documentation\/AWSAppflow\/InternalServerException","preciseIdentifier":"s:10AWSAppflow23InternalServerExceptionV","text":"InternalServerException"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/awsappflow\/describeconnectoroutputerror\/internalserverexception(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AWSAppflow\/documentation\/AWSAppflow\/DescribeConnectorOutputError\/internalServerException(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalServerException"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"InternalServerException","preciseIdentifier":"s:10AWSAppflow23InternalServerExceptionV"},{"kind":"text","text":")"}],"title":"DescribeConnectorOutputError.internalServerException(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:10AWSAppflow28DescribeConnectorOutputErrorO23internalServerExceptionyAcA08InternalgH0VcACmF","modules":[{"name":"AWSAppflow"}]},"hierarchy":{"paths":[["doc:\/\/AWSAppflow\/documentation\/AWSAppflow","doc:\/\/AWSAppflow\/documentation\/AWSAppflow\/DescribeConnectorOutputError"]]},"references":{"doc://AWSAppflow/documentation/AWSAppflow/DescribeConnectorOutputError":{"role":"symbol","title":"DescribeConnectorOutputError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DescribeConnectorOutputError"}],"abstract":[],"identifier":"doc:\/\/AWSAppflow\/documentation\/AWSAppflow\/DescribeConnectorOutputError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DescribeConnectorOutputError"}],"url":"\/documentation\/awsappflow\/describeconnectoroutputerror"},"doc://AWSAppflow/documentation/AWSAppflow/InternalServerException":{"role":"symbol","title":"InternalServerException","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InternalServerException"}],"abstract":[{"type":"text","text":"An internal service error occurred during the processing of your request. Try again later."}],"identifier":"doc:\/\/AWSAppflow\/documentation\/AWSAppflow\/InternalServerException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InternalServerException"}],"url":"\/documentation\/awsappflow\/internalserverexception"},"doc://AWSAppflow/documentation/AWSAppflow":{"role":"collection","title":"AWSAppflow","abstract":[],"identifier":"doc:\/\/AWSAppflow\/documentation\/AWSAppflow","kind":"symbol","type":"topic","url":"\/documentation\/awsappflow"},"doc://AWSAppflow/documentation/AWSAppflow/DescribeConnectorOutputError/internalServerException(_:)":{"role":"symbol","title":"DescribeConnectorOutputError.internalServerException(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalServerException"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"InternalServerException","preciseIdentifier":"s:10AWSAppflow23InternalServerExceptionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AWSAppflow\/documentation\/AWSAppflow\/DescribeConnectorOutputError\/internalServerException(_:)","kind":"symbol","type":"topic","url":"\/documentation\/awsappflow\/describeconnectoroutputerror\/internalserverexception(_:)"}}}