{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalServerException"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager\/InternalServerException","preciseIdentifier":"s:15AWSAuditManager23InternalServerExceptionV","text":"InternalServerException"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/awsauditmanager\/listcontroldomaininsightsoutputerror\/internalserverexception(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager\/ListControlDomainInsightsOutputError\/internalServerException(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalServerException"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"InternalServerException","preciseIdentifier":"s:15AWSAuditManager23InternalServerExceptionV"},{"kind":"text","text":")"}],"title":"ListControlDomainInsightsOutputError.internalServerException(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:15AWSAuditManager36ListControlDomainInsightsOutputErrorO23internalServerExceptionyAcA08InternaljK0VcACmF","modules":[{"name":"AWSAuditManager"}]},"hierarchy":{"paths":[["doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager","doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager\/ListControlDomainInsightsOutputError"]]},"references":{"doc://AWSAuditManager/documentation/AWSAuditManager/ListControlDomainInsightsOutputError":{"role":"symbol","title":"ListControlDomainInsightsOutputError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListControlDomainInsightsOutputError"}],"abstract":[],"identifier":"doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager\/ListControlDomainInsightsOutputError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ListControlDomainInsightsOutputError"}],"url":"\/documentation\/awsauditmanager\/listcontroldomaininsightsoutputerror"},"doc://AWSAuditManager/documentation/AWSAuditManager/ListControlDomainInsightsOutputError/internalServerException(_:)":{"role":"symbol","title":"ListControlDomainInsightsOutputError.internalServerException(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalServerException"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"InternalServerException","preciseIdentifier":"s:15AWSAuditManager23InternalServerExceptionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager\/ListControlDomainInsightsOutputError\/internalServerException(_:)","kind":"symbol","type":"topic","url":"\/documentation\/awsauditmanager\/listcontroldomaininsightsoutputerror\/internalserverexception(_:)"},"doc://AWSAuditManager/documentation/AWSAuditManager/InternalServerException":{"role":"symbol","title":"InternalServerException","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InternalServerException"}],"abstract":[{"type":"text","text":"An internal service error occurred during the processing of your request. Try again later."}],"identifier":"doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager\/InternalServerException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InternalServerException"}],"url":"\/documentation\/awsauditmanager\/internalserverexception"},"doc://AWSAuditManager/documentation/AWSAuditManager":{"role":"collection","title":"AWSAuditManager","abstract":[],"identifier":"doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager","kind":"symbol","type":"topic","url":"\/documentation\/awsauditmanager"}}}