{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailureException"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/InternalFailureException","preciseIdentifier":"s:10AWSAppSync24InternalFailureExceptionV","text":"InternalFailureException"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/awsappsync\/createdatasourceoutputerror\/internalfailureexception(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/CreateDataSourceOutputError\/internalFailureException(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailureException"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"InternalFailureException","preciseIdentifier":"s:10AWSAppSync24InternalFailureExceptionV"},{"kind":"text","text":")"}],"title":"CreateDataSourceOutputError.internalFailureException(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:10AWSAppSync27CreateDataSourceOutputErrorO24internalFailureExceptionyAcA08InternaliJ0VcACmF","modules":[{"name":"AWSAppSync"}]},"hierarchy":{"paths":[["doc:\/\/AWSAppSync\/documentation\/AWSAppSync","doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/CreateDataSourceOutputError"]]},"references":{"doc://AWSAppSync/documentation/AWSAppSync/CreateDataSourceOutputError":{"role":"symbol","title":"CreateDataSourceOutputError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateDataSourceOutputError"}],"abstract":[],"identifier":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/CreateDataSourceOutputError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CreateDataSourceOutputError"}],"url":"\/documentation\/awsappsync\/createdatasourceoutputerror"},"doc://AWSAppSync/documentation/AWSAppSync":{"role":"collection","title":"AWSAppSync","abstract":[],"identifier":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync","kind":"symbol","type":"topic","url":"\/documentation\/awsappsync"},"doc://AWSAppSync/documentation/AWSAppSync/InternalFailureException":{"role":"symbol","title":"InternalFailureException","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InternalFailureException"}],"abstract":[{"type":"text","text":"An internal AppSync error occurred. Try your request again."}],"identifier":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/InternalFailureException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InternalFailureException"}],"url":"\/documentation\/awsappsync\/internalfailureexception"},"doc://AWSAppSync/documentation/AWSAppSync/CreateDataSourceOutputError/internalFailureException(_:)":{"role":"symbol","title":"CreateDataSourceOutputError.internalFailureException(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailureException"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"InternalFailureException","preciseIdentifier":"s:10AWSAppSync24InternalFailureExceptionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/CreateDataSourceOutputError\/internalFailureException(_:)","kind":"symbol","type":"topic","url":"\/documentation\/awsappsync\/createdatasourceoutputerror\/internalfailureexception(_:)"}}}