{"variants":[{"paths":["\/documentation\/awsappsync\/internalfailureexception\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/InternalFailureException\/Equatable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/InternalFailureException\/!=(_:_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"AWSAppSync"}],"role":"collectionGroup","title":"Equatable Implementations"},"hierarchy":{"paths":[["doc:\/\/AWSAppSync\/documentation\/AWSAppSync","doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/InternalFailureException"]]},"references":{"doc://AWSAppSync/documentation/AWSAppSync/InternalFailureException/!=(_:_:)":{"role":"symbol","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/InternalFailureException\/!=(_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/awsappsync\/internalfailureexception\/!=(_:_:)"},"doc://AWSAppSync/documentation/AWSAppSync/InternalFailureException":{"role":"symbol","title":"InternalFailureException","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InternalFailureException"}],"abstract":[{"type":"text","text":"An internal AppSync error occurred. Try your request again."}],"identifier":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/InternalFailureException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InternalFailureException"}],"url":"\/documentation\/awsappsync\/internalfailureexception"},"doc://AWSAppSync/documentation/AWSAppSync":{"role":"collection","title":"AWSAppSync","abstract":[],"identifier":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync","kind":"symbol","type":"topic","url":"\/documentation\/awsappsync"}}}